### ISSUE TITLE
Potential typo in section 1.3 of readme

### ISSUE THREAD

**Issue by tomplex** [mm-mansour/Fast-Pandas#1]
Hey there,

Thanks for all the work you put into this, it will be a great reference in the future. 

I noticed something that could be either a typo or an overlooked error - or I could just be misunderstanding. In [section 1.3](https://github.com/mm-mansour/Fast-Pandas/blob/master/README.md#13---selecting-rows) of the readme, it seems like you've swapped the contents of the `query_selection` and `bracket_selection` functions:

```
def query_selection(df):
    return df[(df["A"] > 0) & (df["A"] < 100)]

def bracket_selection(df):
    return df.query("A > 0 and A < 100")
```

It seems like `query_selection` should be making a call to the `df.query()` method, and `bracket_selection` should be using `[]` to select data. If this isn't the case, then I'd argue you should probably use different or more explicit function names, as I definitely got the wrong impression from your current names. =)

Finally, if this was unintentional, I'd be curious as to whether the benchmarks were actually reversed, or if this was just a typo in creating the write-up.

Thanks again!

**Comment by mm-mansour** [comment]
Hello,
Thanks a lot for such a keen note, the names were swapped unintentionally, I have just fixed it. Check out the updated results, the query selection turned out to be the slowest!
