### ISSUE TITLE
Improving the timing even more

### ISSUE THREAD

**Issue by LuckyJosh** [mm-mansour/Fast-Pandas#3]
I dont know the implementation details of `np.mean` and `df["A"].mean()` but I guess that `np.mean(df["A"])` is slow because numpy has to cast the `pd.Series` in some way.
Using `np.mean(df["A"].values)` is probably always faster, especially for large arrays.

**Comment by asdf8601** [comment]
Yes, actually I forked this project to work on that point [here](https://github.com/mmngreco/Fast-Pandas/tree/master/exports). The reason: if the object passed to a numpy function is not a numpy object then it tries to access method with the same function name that you are trying to use. So when it does run `np.sum(df['a']]` actually it uses the `sum` of pandas instead.

You can see that in the [numpy code](https://github.com/numpy/numpy/blob/master/numpy/core/fromnumeric.py#L70).

Times are fairer with numpy.

PS: Sorry for my english. :-(

**Comment by LuckyJosh** [comment]
There is no need to apologize, your english is fine. 😉

**Comment by mm-mansour** [comment]
Actually ```np.mean(df["A"])``` is slower because it calls ```df["A"].mean()```, just as @mmngreco mentioned.
I have added ```df["A"].values``` to mean and all other functions, check them out and thanks a lot for the suggestions.
