### ISSUE TITLE
Either legend is wrong or bullet points are wrong

### ISSUE THREAD

**Issue by volker48** [mm-mansour/Fast-Pandas#4]
In the selection section these bullet points don't match the graph according to the legend.

* loc and query selections are identical in performance.
* Square bracket selection is the slowest method. 

According to the graph it looks like loc and square brackets are identical in performance. It looks like query is the slowest method. I'm not sure if the issue is with the legend in the graph or the bullet points.

**Comment by mm-mansour** [comment]
The codes for query selection and bracket selection were swapped as reported in #1 . The code and the plot were fixed; however, I forgot to fix the bullet points. I just did.

**Comment by volker48** [comment]
👍
